In [87]:
import pandas as pd
import numpy as np

In [88]:
pd.set_option('display.min_rows',1000)
pd.set_option('display.max_columns',50)
pd.set_option('display.max_colwidth',100)

In [89]:
df = pd.read_csv('global_superstore_2016.csv', encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11-11-2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,Oklahoma,United States,Central US,USCA,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.77,High
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,New South Wales,Australia,Oceania,Asia Pacific,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,Queensland,Australia,Oceania,Asia Pacific,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,Berlin,Germany,Western Europe,Europe,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.16,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,Dakar,Senegal,Western Africa,Africa,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.04,Critical

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  object
 10  State           51290 non-null  object
 11  Country         51290 non-null  object
 12  Region          51290 non-null  object
 13  Market          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  object
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  object
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(3), int64(2), object(19)
memory usage: 9.4+ MB

In [91]:
df.describe()

            Row ID   Postal Code      Quantity      Discount  Shipping Cost
count  51290.00000   9994.000000  51290.000000  51290.000000   51290.000000
mean   25645.50000  55190.379428      3.476545      0.142908      26.478567
std    14806.29199  32063.693350      2.278766      0.212280      57.251373
min        1.00000   1040.000000      1.000000      0.000000       1.002000
25%    12823.25000  23223.000000      2.000000      0.000000       2.610000
50%    25645.50000  56430.500000      3.000000      0.000000       7.790000
75%    38467.75000  90008.000000      5.000000      0.200000      24.450000
max    51290.00000  99301.000000     14.000000      0.850000     933.570000

In [92]:
#converting 'Order Date' and 'Ship Date' to datetime objects
order_date = df['Order Date'].tolist()
ship_date = df['Ship Date'].tolist()
order_datetime = pd.to_datetime(order_date)
ship_datetime = pd.to_datetime(ship_date)

print(order_datetime)

print(ship_datetime)

DatetimeIndex(['2014-11-11', '2014-02-05', '2014-10-17', '2014-01-28',
               '2014-11-05', '2014-06-28', '2012-11-06', '2013-04-14',
               '2014-11-11', '2012-03-06',
               ...
               '2014-07-09', '2015-06-09', '2015-08-05', '2015-05-30',
               '2013-12-28', '2015-06-19', '2014-05-06', '2012-08-26',
               '2013-02-17', '2013-05-22'],
              dtype='datetime64[ns]', length=51290, freq=None)
DatetimeIndex(['2014-11-13', '2014-02-07', '2014-10-18', '2014-01-30',
               '2014-11-06', '2014-07-01', '2012-11-08', '2013-04-18',
               '2014-11-13', '2012-03-07',
               ...
               '2014-07-09', '2015-06-11', '2015-08-10', '2015-05-30',
               '2013-12-31', '2015-06-19', '2014-05-10', '2012-08-31',
               '2013-02-21', '2013-05-26'],
              dtype='datetime64[ns]', length=51290, freq=None)

In [93]:
Order_Date = pd.Series(order_datetime, name='Order_Date')
Ship_Date = pd. Series(ship_datetime, name='Ship_Date')

In [94]:
df.columns.values

array(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'], dtype=object)

In [95]:
# Drop unwanted columns
df.drop(columns=['Row ID','Order Date','Ship Date','Customer ID','Postal Code'], inplace=True)

In [96]:
df.head()

,Order ID,Ship Mode,Customer Name,Segment,City,State,Country,Region,Market,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,CA-2014-AB10015140-41954,First Class,Aaron Bergman,Consumer,Oklahoma City,Oklahoma,United States,Central US,USCA,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.77,High
1,IN-2014-JR162107-41675,Second Class,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,Oceania,Asia Pacific,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical
2,IN-2014-CR127307-41929,First Class,Craig Reiter,Consumer,Brisbane,Queensland,Australia,Oceania,Asia Pacific,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium
3,ES-2014-KM1637548-41667,First Class,Katherine Murray,Home Office,Berlin,Berlin,Germany,Western Europe,Europe,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.16,Medium
4,SG-2014-RH9495111-41948,Same Day,Rick Hansen,Consumer,Dakar,Dakar,Senegal,Western Africa,Africa,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.04,Critical

In [97]:
data = pd.concat([df,Order_Date,Ship_Date], axis=1)
data.head()

,Order ID,Ship Mode,Customer Name,Segment,City,State,Country,Region,Market,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Order_Date,Ship_Date
0,CA-2014-AB10015140-41954,First Class,Aaron Bergman,Consumer,Oklahoma City,Oklahoma,United States,Central US,USCA,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.77,High,2014-11-11,2014-11-13
1,IN-2014-JR162107-41675,Second Class,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,Oceania,Asia Pacific,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical,2014-02-05,2014-02-07
2,IN-2014-CR127307-41929,First Class,Craig Reiter,Consumer,Brisbane,Queensland,Australia,Oceania,Asia Pacific,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium,2014-10-17,2014-10-18
3,ES-2014-KM1637548-41667,First Class,Katherine Murray,Home Office,Berlin,Berlin,Germany,Western Europe,Europe,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.16,Medium,2014-01-28,2014-01-30
4,SG-2014-RH9495111-41948,Same Day,Rick Hansen,Consumer,Dakar,Dakar,Senegal,Western Africa,Africa,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.04,Critical,2014-11-05,2014-11-06

In [98]:
#checking columns 'Sales' and 'Profit' for $ symbol
if data['Sales'].str.contains('$').any():
  print("yes, $ is present in column 'Sales'")

if data['Profit'].str.contains('$').any():
  print("yes, $ is present in column 'Profit'")

yes, $ is present in column 'Sales'
yes, $ is present in column 'Profit'

In [99]:
#Cleaning columns 'Sales' and 'Profit' off symbols
data['Sales'] = data['Sales'].str.replace('$', '', regex=True)
data['Sales'] = data['Sales'].str.replace(',', '', regex=True)
data['Sales'] = data['Sales'].str.replace('(', '', regex=True)
data['Sales'] = data['Sales'].str.replace(')', '', regex=True)

data['Profit'] = data['Profit'].str.replace('$', '', regex=True)
data['Profit'] = data['Profit'].str.replace(',', '', regex=True)
data['Profit'] = data['Profit'].str.replace('(', '', regex=True)
data['Profit'] = data['Profit'].str.replace(')', '', regex=True)

print(data['Sales'][:10])

print(data['Profit'][:10])

0     221.98
1    3709.40
2    5175.17
3    2892.51
4    2832.96
5    2862.68
6    1822.08
7    5244.84
8     341.96
9      48.71
Name: Sales, dtype: object
0     62.15
1     288.77
2    919.97
3      96.54
4    311.52
5    763.28
6    564.84
7    996.48
8     54.71
9      5.48
Name: Profit, dtype: object

In [100]:
#converting the columns into numeric and to 'int'
data['Sales'] = pd.to_numeric(data['Sales'])
data['Profit'] = pd.to_numeric(data['Profit'])

data['Sales'] = data['Sales'].astype(int)
data['Profit'] = data['Profit'].astype(int)

print(type(data['Sales'][0]))
print(type(data['Profit'][0]))

<class 'numpy.int64'>
<class 'numpy.int64'>

**Counting the number of orders that crossed the shipping cost of 500**

In [101]:
cond1 = (data['Shipping Cost']>500.00)
shipping500 = data[cond1]

In [102]:
len(shipping500['Order ID'])

120

In [103]:
shipping500.shape

(120, 21)

**Counting number of segments, countries, regions, markets, catagories and sub-catagories present**

In [104]:
data['Segment'].value_counts()

Consumer       26518
Corporate      15429
Home Office     9343
Name: Segment, dtype: int64

In [105]:
len(data['Country'].value_counts())

165

In [106]:
data['Market'].value_counts()

Asia Pacific    14302
Europe          11729
USCA            10378
LATAM           10294
Africa           4587
Name: Market, dtype: int64

In [107]:
data['Category'].value_counts()

Office Supplies    31289
Technology         10141
Furniture           9860
Name: Category, dtype: int64

In [108]:
data['Sub-Category'].value_counts()

Binders        6146
Storage        5049
Art            4864
Paper          3492
Chairs         3434
Phones         3357
Furnishings    3154
Accessories    3075
Fasteners      2601
Labels         2601
Bookcases      2411
Supplies       2407
Envelopes      2387
Copiers        2223
Appliances     1742
Machines       1486
Tables          861
Name: Sub-Category, dtype: int64

In [109]:
len(data['Sub-Category'].value_counts())

17

**List of Order ID where Indian Customers have bought things under 'Technology'**

In [110]:
cond2 = (data['Country'] == 'India') & (data['Category'] == 'Technology')
indian_orderid = data[cond2]
indian_orderid

,Order ID,Ship Mode,Customer Name,Segment,City,State,Country,Region,Market,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Order_Date,Ship_Date
41,IN-2015-BF1100558-42319,Standard Class,Barry Franz,Home Office,Gorakhpur,Haryana,India,Southern Asia,Asia Pacific,TEC-PH-5269,Technology,Phones,"Motorola Smart Phone, with Caller ID",4518,7,0.0,632,658.69,High,2015-11-11,2015-11-15
48,IN-2015-SW2027558-42125,Same Day,Scott Williamson,Consumer,Jamshedpur,Jharkhand,India,Southern Asia,Asia Pacific,TEC-MA-5007,Technology,Machines,"Konica Inkjet, White",2174,7,0.0,500,637.86,Critical,2015-05-01,2015-05-01
55,IN-2013-SG2047058-41424,First Class,Sheri Gordon,Consumer,Bhopal,Madhya Pradesh,India,Southern Asia,Asia Pacific,TEC-CO-4590,Technology,Copiers,"Hewlett Wireless Fax, Color",1526,4,0.0,732,625.77,Critical,2013-05-30,2013-05-31
90,IN-2013-GP1474058-41419,Second Class,Guy Phonely,Corporate,Delhi,Delhi,India,Southern Asia,Asia Pacific,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",1916,3,0.0,498,548.40,Critical,2013-05-25,2013-05-28
130,IN-2014-SV2081558-41968,First Class,Stuart Van,Corporate,Vadodara,Gujarat,India,Southern Asia,Asia Pacific,TEC-CO-4577,Technology,Copiers,"Hewlett Fax Machine, High-Speed",1590,5,0.0,572,493.20,Critical,2014-11-25,2014-11-27
224,IN-2015-AP1072058-42284,Standard Class,Anne Pryor,Home Office,Jabalpur,Madhya Pradesh,India,Southern Asia,Asia Pacific,TEC-PH-5269,Technology,Phones,"Motorola Smart Phone, with Caller ID",2582,4,0.0,361,404.08,High,2015-10-07,2015-10-11
225,IN-2015-CR1282058-42294,Standard Class,Cyra Reiten,Home Office,Patna,Bihar,India,Southern Asia,Asia Pacific,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",3194,5,0.0,830,403.97,High,2015-10-17,2015-10-21
250,IN-2012-AB1010558-41270,First Class,Adrian Barton,Consumer,Kochi,Kerala,India,Southern Asia,Asia Pacific,TEC-CO-6010,Technology,Copiers,"Sharp Wireless Fax, Digital",1066,3,0.0,394,383.68,Critical,2012-12-27,2012-12-28
313,IN-2014-CA1277558-41802,Standard Class,Cynthia Arntzen,Consumer,Kota,Chhattisgarh,India,Southern Asia,Asia Pacific,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID",5751,9,0.0,2817,353.85,Medium,2014-06-12,2014-06-17
380,IN-2015-AF1088558-42222,Second Class,Art Foster,Consumer,Salem,Tamil Nadu,India,Southern Asia,Asia Pacific,TEC-PH-3148,Technology,Phones,"Apple Smart Phone, Full Size",2550,4,0.0,280,326.32,High,2015-08-06,2015-08-09
392,IN-2012-CL1270058-41226,Standard Class,Craig Leslie,Home Office,Kulti,West Bengal,India,Southern Asia,Asia Pacific,TEC-PH-5268,Technology,Phones,"Motorola Smart Phone, Full Size",4498,7,0.0,674,323.75,Medium,2012-11-13,2012-11-19
404,IN-2012-MG1820558-40962,First Class,Mitch Gastineau,Corporate,Thane,Maharashtra,India,Southern Asia,Asia Pacific,TEC-CO-4590,Technology,Copiers,"Hewlett Wireless Fax, Color",1526,4,0.0,732,319.53,High,2012-02-23,2012-02-26
408,IN-2015-CY1274558-42300,First Class,Craig Yedwab,Corporate,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-CO-4578,Technology,Copiers,"Hewlett Fax Machine, Laser",959,3,0.0,460,317.81,Critical,2015-10-23,2015-10-25
422,IN-2014-MR1754558-41954,Same Day,Mathew Reese,Home Office,Jodhpur,Rajasthan,India,Southern Asia,Asia Pacific,TEC-CO-3683,Technology,Copiers,"Canon Fax and Copier, Digital",763,4,0.0,381,313.66,Critical,2014-11-11,2014-11-11
445,IN-2015-CC1247558-42129,Second Class,Cindy Chapman,Consumer,Bhavnagar,Gujarat,India,Southern Asia,Asia Pacific,TEC-CO-3596,Technology,Copiers,"Brother Fax Machine, Digital",1272,4,0.0,534,305.27,High,2015-05-05,2015-05-07
460,IN-2013-NZ1856558-41398,Second Class,Nick Zandusky,Home Office,Jaipur,Rajasthan,India,Southern Asia,Asia Pacific,TEC-CO-3678,Technology,Copiers,"Canon Copy Machine, Color",2372,9,0.0,0,302.82,High,2013-05-04,2013-05-06
480,IN-2012-DM1352558-41123,Second Class,Don Miller,Corporate,Muzaffarpur,Bihar,India,Southern Asia,Asia Pacific,TEC-PH-5813,Technology,Phones,"Samsung Audio Dock, Full Size",840,5,0.0,319,296.68,Critical,2012-08-02,2012-08-05
504,IN-2013-DL1333058-41328,Standard Class,Denise Leinenbach,Consumer,Nagpur,Maharashtra,India,Southern Asia,Asia Pacific,TEC-PH-5840,Technology,Phones,"Samsung Smart Phone, Full Size",3187,5,0.0,541,289.17,Medium,2013-02-23,2013-02-28
513,IN-2013-BW1111058-41404,First Class,Bart Watters,Corporate,Jhansi,Uttar Pradesh,India,Southern Asia,Asia Pacific,TEC-MA-5014,Technology,Machines,"Konica Printer, Durable",1607,6,0.0,482,286.74,High,2013-05-10,2013-05-12
514,IN-2014-JE1561058-41895,Same Day,Jim Epp,Corporate,Amravati,Maharashtra,India,Southern Asia,Asia Pacific,TEC-PH-5336,Technology,Phones,"Nokia Audio Dock, Full Size",840,5,0.0,260,286.67,Critical,2014-09-13,2014-09-13
569,IN-2013-LW1682558-41376,Second Class,Laurel Workman,Corporate,Nasik,Maharashtra,India,Southern Asia,Asia Pacific,TEC-CO-4789,Technology,Copiers,"HP Wireless Fax, Color",723,2,0.0,332,273.63,Critical,2013-04-12,2013-04-14
612,IN-2012-DP1316558-41173,Second Class,David Philippe,Consumer,Thane,Maharashtra,India,Southern Asia,Asia Pacific,TEC-PH-5839,Technology,Phones,"Samsung Smart Phone, Cordless",1917,3,0.0,690,261.08,High,2012-09-21,2012-09-26
743,IN-2013-CS1246058-41609,Standard Class,Chuck Sachs,Consumer,Aligarh,Uttar Pradesh,India,Southern Asia,Asia Pacific,TEC-CO-5997,Technology,Copiers,"Sharp Fax Machine, Color",2673,9,0.0,26,237.05,Medium,2013-12-01,2013-12-07
770,IN-2013-CC1268558-41619,Standard Class,Craig Carroll,Consumer,Vijayawada,Andhra Pradesh,India,Southern Asia,Asia Pacific,TEC-PH-3805,Technology,Phones,"Cisco Smart Phone, Cordless",1302,2,0.0,182,234.15,High,2013-12-11,2013-12-15
782,IN-2015-JW1522058-42101,Standard Class,Jane Waco,Corporate,Mangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-PH-3807,Technology,Phones,"Cisco Smart Phone, with Caller ID",3271,5,0.0,1341,232.45,High,2015-04-07,2015-04-12
813,IN-2013-TB2119058-41552,Standard Class,Thomas Brumley,Home Office,Allahabad,Uttar Pradesh,India,Southern Asia,Asia Pacific,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID",2544,4,0.0,865,226.81,Medium,2013-10-05,2013-10-09
822,IN-2014-LR1691558-41899,First Class,Lena Radford,Consumer,Gorakhpur,Haryana,India,Southern Asia,Asia Pacific,TEC-PH-5354,Technology,Phones,"Nokia Smart Phone, Cordless",1908,3,0.0,534,225.58,High,2014-09-17,2014-09-20
830,IN-2015-DM1334558-42182,Second Class,Denise Monton,Corporate,Varanasi,Uttar Pradesh,India,Southern Asia,Asia Pacific,TEC-CO-3588,Technology,Copiers,"Brother Copy Machine, High-Speed",2098,8,0.0,860,224.28,Medium,2015-06-27,2015-07-02
858,IN-2014-ZC2191058-41760,Standard Class,Zuschuss Carroll,Consumer,Tiruppur,Tamil Nadu,India,Southern Asia,Asia Pacific,TEC-CO-3707,Technology,Copiers,"Canon Wireless Fax, Color",3040,8,0.0,1155,219.74,Medium,2014-05-01,2014-05-05
943,IN-2014-DK1298558-41863,Standard Class,Darren Koutras,Consumer,Delhi,Delhi,India,Southern Asia,Asia Pacific,TEC-PH-5355,Technology,Phones,"Nokia Smart Phone, Full Size",3180,5,0.0,381,209.29,Medium,2014-08-12,2014-08-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26688,IN-2015-RB1933058-42164,Standard Class,Randy Bradley,Consumer,Korba,Chhattisgarh,India,Southern Asia,Asia Pacific,TEC-AC-5883,Technology,Accessories,"SanDisk Mouse, USB",77,2,0.0,0,7.18,Low,2015-06-09,2015-06-16
26793,IN-2014-MG1820558-41982,Standard Class,Mitch Gastineau,Corporate,Panihati,West Bengal,India,Southern Asia,Asia Pacific,TEC-PH-5815,Technology,Phones,"Samsung Audio Dock, with Caller ID",166,1,0.0,11,7.11,Medium,2014-12-09,2014-12-16
26994,ID-2012-BF1097558-41174,Second Class,Barbara Fisher,Corporate,Mumbai,Maharashtra,India,Southern Asia,Asia Pacific,TEC-AC-5865,Technology,Accessories,"SanDisk Keyboard, Erganomic",118,3,0.5,4,6.99,Medium,2012-09-22,2012-09-26
27369,IN-2012-AS1009058-41136,Standard Class,Adam Shillingsburg,Consumer,Raipur,Rajasthan,India,Southern Asia,Asia Pacific,TEC-AC-5200,Technology,Accessories,"Memorex Keyboard, Erganomic",69,1,0.0,26,6.79,Medium,2012-08-15,2012-08-19
27644,IN-2015-AJ1079558-42307,Same Day,Anthony Johnson,Corporate,Kochi,Kerala,India,Southern Asia,Asia Pacific,TEC-PH-3134,Technology,Phones,"Apple Headset, VoIP",293,4,0.0,8,6.64,High,2015-10-30,2015-10-30
27928,ID-2013-CR1273058-41517,Standard Class,Craig Reiter,Consumer,Mumbai,Maharashtra,India,Southern Asia,Asia Pacific,TEC-CO-3600,Technology,Copiers,"Brother Ink, Digital",73,1,0.5,1,6.50,High,2013-08-31,2013-09-04
28668,IN-2015-NZ1856558-42137,Standard Class,Nick Zandusky,Home Office,Hyderabad,Telangana,India,Southern Asia,Asia Pacific,TEC-MA-5539,Technology,Machines,"Panasonic Calculator, Red",94,2,0.0,33,6.12,Medium,2015-05-13,2015-05-17
28766,IN-2014-IM1507058-41812,Standard Class,Irene Maddox,Consumer,Akola,Maharashtra,India,Southern Asia,Asia Pacific,TEC-PH-3134,Technology,Phones,"Apple Headset, VoIP",73,1,0.0,2,6.07,Medium,2014-06-22,2014-06-27
28944,IN-2012-RH1951058-40961,Standard Class,Rick Huthwaite,Home Office,Kota,Rajasthan,India,Southern Asia,Asia Pacific,TEC-AC-5124,Technology,Accessories,"Logitech Memory Card, USB",207,2,0.0,43,5.99,Medium,2012-02-22,2012-02-26
29136,IN-2014-KH1633058-41828,Standard Class,Katharine Harms,Corporate,Darbhanga,Bihar,India,Southern Asia,Asia Pacific,TEC-AC-5132,Technology,Accessories,"Logitech Numeric Keypad, Programmable",95,2,0.0,17,5.90,Medium,2014-07-08,2014-07-13
29233,IN-2015-LD1700558-42101,Standard Class,Lisa DeCherney,Consumer,Kukatpalli,Telangana,India,Southern Asia,Asia Pacific,TEC-AC-5883,Technology,Accessories,"SanDisk Mouse, USB",154,4,0.0,0,5.86,Medium,2015-04-07,2015-04-11
29912,IN-2015-AF1087058-42111,Standard Class,Art Ferguson,Consumer,Saharanpur,Uttar Pradesh,India,Southern Asia,Asia Pacific,TEC-AC-5195,Technology,Accessories,"Memorex Flash Drive, Programmable",61,2,0.0,14,5.53,Medium,2015-04-17,2015-04-22
30184,IN-2014-KB1658558-41994,Standard Class,Ken Black,Corporate,Puducherry,Puducherry,India,Southern Asia,Asia Pacific,TEC-PH-5253,Technology,Phones,"Motorola Headset, VoIP",159,2,0.0,20,5.41,Medium,2014-12-21,2014-12-26
30232,IN-2014-RP1985558-41990,Standard Class,Roy Phan,Corporate,Warangal,Telangana,India,Southern Asia,Asia Pacific,TEC-AC-5889,Technology,Accessories,"SanDisk Numeric Keypad, USB",106,2,0.0,30,5.39,Medium,2014-12-17,2014-12-24
30900,IN-2013-SC2077058-41538,Standard Class,Stewart Carmichael,Corporate,Kamarhati,West Bengal,India,Southern Asia,Asia Pacific,TEC-AC-4153,Technology,Accessories,"Enermax Flash Drive, Programmable",86,2,0.0,3,5.11,Medium,2013-09-21,2013-09-26
31668,IN-2012-JG1580558-41061,Standard Class,John Grady,Corporate,Agra,Uttar Pradesh,India,Southern Asia,Asia Pacific,TEC-AC-3392,Technology,Accessories,"Belkin Mouse, Bluetooth",81,2,0.0,11,4.78,Medium,2012-06-01,2012-06-06
32544,IN-2013-SV2093558-41371,Standard Class,Susan Vittorini,Consumer,Bhavnagar,Gujarat,India,Southern Asia,Asia Pacific,TEC-AC-5201,Technology,Accessories,"Memorex Keyboard, Programmable",72,1,0.0,10,4.45,High,2013-04-07,2013-04-12
33030,IN-2015-DW1358558-42301,Standard Class,Dorothy Wardle,Corporate,Surat,Gujarat,India,Southern Asia,Asia Pacific,TEC-PH-3798,Technology,Phones,"Cisco Office Telephone, VoIP",161,2,0.0,14,4.26,Medium,2015-10-24,2015-10-28
33999,IN-2014-VT2170058-41804,Standard Class,Valerie Takahito,Home Office,Ajmer,Rajasthan,India,Southern Asia,Asia Pacific,TEC-AC-5218,Technology,Accessories,"Memorex Mouse, Programmable",59,2,0.0,14,3.92,Medium,2014-06-14,2014-06-18
34457,IN-2013-ML1826558-41432,Standard Class,Muhammed Lee,Consumer,Nellore,Andhra Pradesh,India,Southern Asia,Asia Pacific,TEC-MA-5012,Technology,Machines,"Konica Phone, White",84,1,0.0,20,3.76,High,2013-06-07,2013-06-11
35688,IN-2015-BS1159058-42179,Second Class,Brendan Sweed,Corporate,Meerut,Uttar Pradesh,India,Southern Asia,Asia Pacific,TEC-AC-3395,Technology,Accessories,"Belkin Mouse, USB",40,1,0.0,13,3.38,Medium,2015-06-24,2015-06-29
35903,IN-2013-JS1568558-41371,Standard Class,Jim Sink,Corporate,Delhi,Delhi,India,Southern Asia,Asia Pacific,TEC-PH-5840,Technology,Phones,"Samsung Smart Phone, Full Size",637,1,0.0,108,3.32,Medium,2013-04-07,2013-04-12
35956,IN-2013-AT1043558-41607,Standard Class,Alyssa Tate,Home Office,Bellary,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-5101,Technology,Accessories,"Logitech Flash Drive, Programmable",32,1,0.0,10,3.30,High,2013-11-29,2013-12-03
35977,IN-2013-MF1825058-41460,Standard Class,Monica Federle,Corporate,Allahabad,Uttar Pradesh,India,Southern Asia,Asia Pacific,TEC-AC-3393,Technology,Accessories,"Belkin Mouse, Erganomic",38,1,0.0,8,3.30,Medium,2013-07-05,2013-07-12
39400,IN-2013-SG2047058-41424,First Class,Sheri Gordon,Consumer,Bhopal,Madhya Pradesh,India,Southern Asia,Asia Pacific,TEC-AC-5099,Technology,Accessories,"Logitech Flash Drive, Bluetooth",30,1,0.0,11,2.39,Critical,2013-05-30,2013-05-31
39631,IN-2013-JR1570058-41441,Standard Class,Jocasta Rupert,Consumer,Kollam,Kerala,India,Southern Asia,Asia Pacific,TEC-AC-4178,Technology,Accessories,"Enermax Numeric Keypad, Bluetooth",114,2,0.0,4,2.33,Medium,2013-06-16,2013-06-22
40262,IN-2014-GZ1447058-41721,Standard Class,Gary Zandusky,Consumer,Ludhiana,Punjab,India,Southern Asia,Asia Pacific,TEC-AC-5221,Technology,Accessories,"Memorex Numeric Keypad, Erganomic",93,2,0.0,42,2.18,Medium,2014-03-23,2014-03-27
42345,IN-2015-CR1282058-42294,Standard Class,Cyra Reiten,Home Office,Patna,Bihar,India,Southern Asia,Asia Pacific,TEC-PH-5838,Technology,Phones,"Samsung Signal Booster, with Caller ID",136,1,0.0,57,1.92,High,2015-10-17,2015-10-21
43976,IN-2015-LD1700558-42101,Standard Class,Lisa DeCherney,Consumer,Kukatpalli,Telangana,India,Southern Asia,Asia Pacific,TEC-CO-3591,Technology,Copiers,"Brother Fax and Copier, Color",385,2,0.0,84,1.77,Medium,2015-04-07,2015-04-11
51172,IN-2014-AS1013558-41817,Standard Class,Adrian Shami,Home Office,Nagercoil,Tamil Nadu,India,Southern Asia,Asia Pacific,TEC-AC-3388,Technology,Accessories,"Belkin Memory Card, Bluetooth",114,1,0.0,32,1.06,Medium,2014-06-27,2014-07-03

In [111]:
list1 = indian_orderid['Order ID'].tolist()
list1

['IN-2015-BF1100558-42319',
 'IN-2015-SW2027558-42125',
 'IN-2013-SG2047058-41424',
 'IN-2013-GP1474058-41419',
 'IN-2014-SV2081558-41968',
 'IN-2015-AP1072058-42284',
 'IN-2015-CR1282058-42294',
 'IN-2012-AB1010558-41270',
 'IN-2014-CA1277558-41802',
 'IN-2015-AF1088558-42222',
 'IN-2012-CL1270058-41226',
 'IN-2012-MG1820558-40962',
 'IN-2015-CY1274558-42300',
 'IN-2014-MR1754558-41954',
 'IN-2015-CC1247558-42129',
 'IN-2013-NZ1856558-41398',
 'IN-2012-DM1352558-41123',
 'IN-2013-DL1333058-41328',
 'IN-2013-BW1111058-41404',
 'IN-2014-JE1561058-41895',
 'IN-2013-LW1682558-41376',
 'IN-2012-DP1316558-41173',
 'IN-2013-CS1246058-41609',
 'IN-2013-CC1268558-41619',
 'IN-2015-JW1522058-42101',
 'IN-2013-TB2119058-41552',
 'IN-2014-LR1691558-41899',
 'IN-2015-DM1334558-42182',
 'IN-2014-ZC2191058-41760',
 'IN-2014-DK1298558-41863',
 'IN-2014-MS1798058-41801',
 'IN-2014-LB1679558-41893',
 'IN-2014-CC1237058-41710',
 'IN-2014-GZ1447058-41721',
 'IN-2014-AS1028558-41877',
 'IN-2012-LR1703558-41195',
 'IN-2013-SW2024558-41425',
 'IN-2013-FG1426058-41509',
 'ID-2012-MG1768058-41219',
 'IN-2012-DH1367558-41233',
 'IN-2012-GT1471058-41158',
 'IN-2013-EC1405058-41605',
 'IN-2014-RA1928558-41863',
 'IN-2015-RB1946558-42326',
 'IN-2014-MG1820558-41853',
 'IN-2014-AM1036058-41664',
 'IN-2012-DM1295558-41142',
 'IN-2013-DP1316558-41623',
 'IN-2013-HH1501058-41576',
 'IN-2015-LB1679558-42033',
 'IN-2013-FG1426058-41509',
 'IN-2014-AB1060058-41858',
 'IN-2015-KW1657058-42083',
 'IN-2014-ZC2191058-41760',
 'IN-2014-BO1135058-41783',
 'IN-2015-GW1460558-42173',
 'IN-2013-NG1843058-41319',
 'IN-2014-AS1013558-41817',
 'IN-2015-JH1618058-42277',
 'IN-2013-MD1786058-41544',
 'IN-2012-BF1121558-40955',
 'IN-2014-AA1064558-41779',
 'ID-2014-MJ1774058-41814',
 'IN-2015-RB1946558-42355',
 'IN-2015-BS1166558-42250',
 'IN-2012-KB1660058-41046',
 'ID-2014-EM1396058-41901',
 'IN-2014-NG1843058-41996',
 'IN-2013-RB1936058-41405',
 'IN-2012-EH1399058-41187',
 'IN-2013-BW1111058-41404',
 'IN-2013-LB1673558-41604',
 'IN-2015-SC2005058-42183',
 'IN-2015-RE1945058-42346',
 'IN-2013-RL1961558-41550',
 'IN-2014-MH1745558-41893',
 'IN-2014-MR1754558-41954',
 'ID-2013-CR1273058-41517',
 'IN-2015-CC1237058-42160',
 'IN-2014-DW1348058-41852',
 'IN-2014-TB2159558-41968',
 'IN-2014-CM1238558-41755',
 'IN-2015-SV2093558-42321',
 'IN-2014-MS1798058-41867',
 'IN-2015-JO1528058-42242',
 'IN-2015-VP2173058-42085',
 'IN-2014-NL1831058-41927',
 'IN-2012-SC2023058-41081',
 'IN-2015-JR1570058-42290',
 'IN-2015-VP2176058-42293',
 'IN-2012-JS1588058-41058',
 'IN-2012-DL1349558-41215',
 'IN-2012-EH1399058-41187',
 'IN-2015-GW1460558-42173',
 'IN-2012-BM1178558-41124',
 'IN-2012-EH1412558-41066',
 'IN-2012-MV1819058-40988',
 'IN-2014-SZ2003558-41776',
 'IN-2012-AS1028558-41221',
 'IN-2015-AP1072058-42284',
 'IN-2013-AR1034558-41531',
 'IN-2013-RO1978058-41296',
 'IN-2013-BF1102058-41556',
 'IN-2012-EH1399058-41187',
 'IN-2015-CP1234058-42239',
 'IN-2013-TB2119058-41552',
 'IN-2012-LC1696058-41241',
 'IN-2013-AR1054058-41275',
 'IN-2014-CS1213058-41816',
 'IN-2015-DJ1363058-42153',
 'IN-2015-AO1081058-42224',
 'IN-2013-AR1057058-41632',
 'IN-2014-VT2170058-41804',
 'IN-2015-CC1210058-42237',
 'IN-2012-DA1345058-41264',
 'IN-2012-LA1678058-41247',
 'IN-2015-MC1757558-42188',
 'IN-2015-BF1100558-42319',
 'IN-2013-CD1228058-41311',
 'IN-2014-JJ1544558-41723',
 'IN-2013-JH1618058-41608',
 'IN-2015-MK1816058-42330',
 'IN-2012-AH1046558-41059',
 'IN-2015-LF1718558-42320',
 'IN-2013-BW1111058-41404',
 'IN-2012-ST2053058-41150',
 'IN-2015-PS1897058-42117',
 'IN-2013-JG1531058-41447',
 'IN-2014-TC2147558-41753',
 'IN-2013-NC1834058-41385',
 'IN-2015-CR1282058-42294',
 'IN-2014-VT2170058-41804',
 'IN-2015-ED1388558-42168',
 'IN-2012-GH1448558-41191',
 'IN-2015-CS1250558-42173',
 'IN-2015-Co1264058-42326',
 'IN-2014-DV1304558-41865',
 'IN-2013-FG1426058-41509',
 'IN-2013-AB1001558-41284',
 'IN-2014-MZ1751558-41775',
 'IN-2013-PK1891058-41567',
 'IN-2015-EM1414058-42194',
 'IN-2012-EH1412558-41066',
 'IN-2015-AP1072058-42284',
 'IN-2014-MG1820558-41853',
 'IN-2015-TT2146058-42222',
 'IN-2013-PF1916558-41550',
 'IN-2015-DH1367558-42202',
 'IN-2015-PN1877558-42228',
 'IN-2014-JF1519058-41900',
 'IN-2012-JG1580558-41061',
 'IN-2014-TM2101058-41895',
 'IN-2014-DK1309058-41954',
 'IN-2015-LF1718558-42320',
 'IN-2015-JW1607558-42013',
 'IN-2014-TP2141558-41641',
 'IN-2014-LB1679558-41893',
 'IN-2012-TS2134058-41161',
 'IN-2014-KE1642058-41997',
 'IN-2015-TT2146058-42222',
 'IN-2013-ML1741058-41572',
 'IN-2014-RA1928558-41863',
 'IN-2012-HR1483058-41171',
 'IN-2015-AC1061558-42067',
 'IN-2015-DB1340558-42094',
 'IN-2015-DR1294058-42283',
 'IN-2015-EM1414058-42194',
 'IN-2015-BE1145558-42342',
 'IN-2015-RR1931558-42225',
 'IN-2015-CC1268558-42228',
 'IN-2015-AF1087058-42090',
 'IN-2012-BD1163558-41259',
 'IN-2012-SN2056058-41132',
 'IN-2015-KD1634558-42029',
 'IN-2014-TP2141558-41641',
 'IN-2013-AO1081058-41460',
 'IN-2013-FH1427558-41566',
 'IN-2013-AJ1094558-41299',
 'IN-2013-DW1358558-41532',
 'IN-2015-LT1711058-42126',
 'IN-2013-PO1885058-41500',
 'IN-2015-CP1234058-42202',
 'IN-2013-MC1727558-41611',
 'IN-2013-JF1549058-41559',
 'IN-2015-BS1175558-42064',
 'IN-2014-AH1007558-41896',
 'IN-2013-JS1568558-41371',
 'IN-2014-GZ1454558-41733',
 'IN-2013-LS1720058-41286',
 'IN-2014-PO1885058-41778',
 'IN-2015-SC2030558-42283',
 'IN-2013-JM1553558-41567',
 'ID-2012-MK1790558-41038',
 'ID-2014-RH1951058-41651',
 'IN-2013-JF1549058-41360',
 'IN-2013-JS1568558-41371',
 'ID-2014-PR1888058-41964',
 'IN-2015-AS1013558-42229',
 'IN-2012-CA1277558-41214',
 'IN-2012-BM1178558-41124',
 'IN-2015-PB1880558-42314',
 'IN-2015-NZ1856558-42137',
 'IN-2014-SC2002058-41851',
 'IN-2015-BG1103558-42253',
 'IN-2015-HD1478558-42229',
 'IN-2015-JK1562558-42249',
 'IN-2013-TS2150558-41500',
 'IN-2015-CC1267058-42342',
 'IN-2015-LC1714058-42166',
 'IN-2015-GM1469558-42259',
 'IN-2015-JM1586558-42301',
 'IN-2014-PF1916558-41961',
 'IN-2015-AC1061558-42067',
 'IN-2015-BT1148558-42129',
 'IN-2012-JS1588058-41058',
 'IN-2014-DW1319558-41857',
 'IN-2012-JD1601558-41086',
 'IN-2015-VG2180558-42273',
 'IN-2015-GH1442558-42150',
 'IN-2015-JK1573058-42122',
 'IN-2013-PO1885058-41500',
 'IN-2014-GH1441058-41865',
 'IN-2013-RW1963058-41405',
 'IN-2014-AC1045058-41814',
 'IN-2013-RW1963058-41405',
 'IN-2014-JF1519058-41944',
 'ID-2013-VF2171558-41566',
 'IN-2013-MA1756058-41275',
 'IN-2014-AP1072058-41926',
 'IN-2012-SP2092058-41219',
 'IN-2013-RM1975058-41444',
 'IN-2015-BG1103558-42253',
 'IN-2013-MH1745558-41590',
 'IN-2014-SP2054558-42003',
 'IN-2014-SF2020058-41919',
 'IN-2012-DH1367558-41233',
 'IN-2014-JR1621058-41850',
 'IN-2015-TB2162558-42048',
 'IN-2013-KT1648058-41639',
 'ID-2014-DR1288058-41870',
 'IN-2012-AH1019558-41263',
 'IN-2015-BF1100558-42319',
 'IN-2014-FA1423058-41807',
 'IN-2013-JE1571558-41519',
 'IN-2015-WB2185058-42273',
 'IN-2015-BS1136558-42369',
 'IN-2012-KC1625558-41149',
 'IN-2015-CC1210058-42237',
 'IN-2014-RA1928558-41863',
 'IN-2015-ON1871558-42244',
 'IN-2012-GM1444058-41200',
 'IN-2015-MS1777058-42218',
 'IN-2013-LP1709558-41609',
 'IN-2015-SS2059058-42115',
 'IN-2013-ML1826558-41503',
 'IN-2015-AW1084058-42083',
 'IN-2015-LS1697558-42119',
 'IN-2015-HG1484558-42339',
 'IN-2013-EL1373558-41409',
 'IN-2015-AG1090058-42172',
 'IN-2012-VM2183558-41240',
 'IN-2015-JP1546058-42258',
 'IN-2013-AR1054058-41550',
 'IN-2015-PF1916558-42093',
 'IN-2012-EH1412558-41066',
 'IN-2012-AB1010558-41270',
 'IN-2014-JR1621058-41850',
 'IN-2013-TB2152058-41430',
 'IN-2013-MA1799558-41565',
 'IN-2013-ON1871558-41636',
 'IN-2015-Co1264058-42326',
 'IN-2012-SN2056058-41132',
 'IN-2015-DM1334558-42146',
 'IN-2013-MM1828058-41543',
 'IN-2015-EM1406558-42353',
 'IN-2015-RB1946558-42326',
 'IN-2014-HG1502558-41692',
 'IN-2015-Co1264058-42326',
 'IN-2015-SC2038058-42074',
 'IN-2014-CM1238558-41755',
 'IN-2015-NK1849058-42154',
 'IN-2013-JS1568558-41371',
 'IN-2012-AG1049558-41054',
 'IN-2014-JK1562558-41766',
 'IN-2012-RE1945058-41076',
 'IN-2015-LB1679558-42064',
 'IN-2012-VG2179058-40997',
 'IN-2015-SC2002058-42279',
 'IN-2015-JR1570058-42290',
 'IN-2014-CR1273058-41809',
 'IN-2015-JB1604558-42019',
 'IN-2015-DB1340558-42094',
 'IN-2012-SG2008058-41208',
 'IN-2012-NZ1856558-41271',
 'IN-2012-CW1190558-41145',
 'IN-2015-BD1156058-42325',
 'IN-2015-JK1609058-42258',
 'IN-2014-AS1028558-41877',
 'IN-2014-PW1903058-41999',
 'IN-2014-JR1621058-41850',
 'IN-2015-KD1634558-42029',
 'IN-2014-LC1688558-41940',
 'IN-2013-MA1799558-41565',
 'IN-2015-AW1084058-42083',
 'IN-2014-DJ1342058-41646',
 'IN-2013-SC2023058-41515',
 'IN-2015-HZ1495058-42319',
 'IN-2013-AB1001558-41284',
 'IN-2013-MA1799558-41565',
 'ID-2013-NP1870058-41593',
 'IN-2015-CR1273058-42243',
 'IN-2014-CJ1201058-41865',
 'IN-2014-DK1309058-41954',
 'IN-2012-DP1316558-41173',
 'IN-2012-CL1270058-41226',
 'IN-2013-BG1169558-41436',
 'IN-2015-KD1634558-42029',
 'IN-2014-SC2002058-41842',
 'IN-2012-CA1277558-41214',
 'IN-2013-DL1333058-41328',
 'IN-2012-CL1270058-41226',
 'IN-2015-JP1546058-42258',
 'IN-2013-VM2183558-41599',
 'IN-2015-TM2149058-42026',
 'IN-2015-RB1933058-42164',
 'IN-2014-MG1820558-41982',
 'ID-2012-BF1097558-41174',
 'IN-2012-AS1009058-41136',
 'IN-2015-AJ1079558-42307',
 'ID-2013-CR1273058-41517',
 'IN-2015-NZ1856558-42137',
 'IN-2014-IM1507058-41812',
 'IN-2012-RH1951058-40961',
 'IN-2014-KH1633058-41828',
 'IN-2015-LD1700558-42101',
 'IN-2015-AF1087058-42111',
 'IN-2014-KB1658558-41994',
 'IN-2014-RP1985558-41990',
 'IN-2013-SC2077058-41538',
 'IN-2012-JG1580558-41061',
 'IN-2013-SV2093558-41371',
 'IN-2015-DW1358558-42301',
 'IN-2014-VT2170058-41804',
 'IN-2013-ML1826558-41432',
 'IN-2015-BS1159058-42179',
 'IN-2013-JS1568558-41371',
 'IN-2013-AT1043558-41607',
 'IN-2013-MF1825058-41460',
 'IN-2013-SG2047058-41424',
 'IN-2013-JR1570058-41441',
 'IN-2014-GZ1447058-41721',
 'IN-2015-CR1282058-42294',
 'IN-2015-LD1700558-42101',
 'IN-2014-AS1013558-41817']

**Counting number of people from the state Karnataka who have bought the things under category 'Technology'**

In [112]:
cond3 = (data['Country']=='India') & (data['Category']=='Technology') & (data['State']=='Karnataka')
data_state = data[cond3]
data_state

,Order ID,Ship Mode,Customer Name,Segment,City,State,Country,Region,Market,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Order_Date,Ship_Date
408,IN-2015-CY1274558-42300,First Class,Craig Yedwab,Corporate,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-CO-4578,Technology,Copiers,"Hewlett Fax Machine, Laser",959,3,0.0,460,317.81,Critical,2015-10-23,2015-10-25
782,IN-2015-JW1522058-42101,Standard Class,Jane Waco,Corporate,Mangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-PH-3807,Technology,Phones,"Cisco Smart Phone, with Caller ID",3271,5,0.0,1341,232.45,High,2015-04-07,2015-04-12
1957,IN-2014-RA1928558-41863,Standard Class,Ralph Arnett,Consumer,Mangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-CO-4791,Technology,Copiers,"HP Wireless Fax, High-Speed",1075,3,0.0,344,136.45,High,2014-08-12,2014-08-16
2364,IN-2014-BO1135058-41783,Standard Class,Bill Overfelt,Corporate,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-CO-3608,Technology,Copiers,"Brother Wireless Fax, Color",1140,3,0.0,0,119.46,Medium,2014-05-24,2014-05-30
3200,IN-2014-CM1238558-41755,Second Class,Christopher Martinez,Consumer,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-CO-4769,Technology,Copiers,"HP Fax and Copier, Color",697,4,0.0,292,94.93,High,2014-04-26,2014-04-28
5030,IN-2015-MK1816058-42330,Standard Class,Mike Kennedy,Consumer,Mangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-CO-3609,Technology,Copiers,"Brother Wireless Fax, Digital",1892,5,0.0,927,66.30,Medium,2015-11-22,2015-11-26
5132,IN-2012-AH1046558-41059,Same Day,Amy Hunt,Consumer,Belgaum,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-5132,Technology,Accessories,"Logitech Numeric Keypad, Programmable",382,8,0.0,68,65.04,Medium,2012-05-30,2012-05-30
5378,IN-2014-TC2147558-41753,Second Class,Tony Chapman,Home Office,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-PH-5266,Technology,Phones,"Motorola Signal Booster, with Caller ID",286,2,0.0,19,62.00,Critical,2014-04-24,2014-04-26
5572,IN-2015-Co1264058-42326,Standard Class,Corey-Lock,Consumer,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-PH-3807,Technology,Phones,"Cisco Smart Phone, with Caller ID",654,1,0.0,268,60.28,Medium,2015-11-18,2015-11-22
7304,IN-2014-RA1928558-41863,Standard Class,Ralph Arnett,Consumer,Mangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-PH-3139,Technology,Phones,"Apple Office Telephone, Cordless",408,6,0.0,192,46.71,High,2014-08-12,2014-08-16
12782,IN-2013-MA1756058-41275,Standard Class,Matt Abelman,Home Office,Bellary,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-5194,Technology,Accessories,"Memorex Flash Drive, Erganomic",244,9,0.0,65,24.56,High,2013-01-01,2013-01-06
12996,IN-2013-MH1745558-41590,Second Class,Mark Hamilton,Consumer,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-5866,Technology,Accessories,"SanDisk Keyboard, Programmable",414,5,0.0,124,24.00,Medium,2013-11-12,2013-11-17
14278,IN-2014-RA1928558-41863,Standard Class,Ralph Arnett,Consumer,Mangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-MA-6139,Technology,Machines,"StarTech Card Printer, Wireless",163,1,0.0,37,21.12,High,2014-08-12,2014-08-16
16364,IN-2013-TB2152058-41430,Standard Class,Tracy Blumstein,Consumer,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-PH-3127,Technology,Phones,"Apple Audio Dock, Cordless",339,2,0.0,27,17.34,Medium,2013-06-05,2013-06-10
16877,IN-2013-ON1871558-41636,Standard Class,Odella Nelson,Corporate,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-MA-5542,Technology,Machines,"Panasonic Card Printer, Durable",347,2,0.0,163,16.53,Medium,2013-12-28,2014-01-02
17155,IN-2015-Co1264058-42326,Standard Class,Corey-Lock,Consumer,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-4152,Technology,Accessories,"Enermax Flash Drive, Erganomic",196,5,0.0,82,16.11,Medium,2015-11-18,2015-11-22
18314,IN-2015-Co1264058-42326,Standard Class,Corey-Lock,Consumer,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-5872,Technology,Accessories,"SanDisk Memory Card, Bluetooth",224,2,0.0,6,14.51,Medium,2015-11-18,2015-11-22
18733,IN-2014-CM1238558-41755,Second Class,Christopher Martinez,Consumer,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-PH-3817,Technology,Phones,"Cisco Speaker Phone, VoIP",277,2,0.0,38,13.96,High,2014-04-26,2014-04-28
21482,IN-2014-PW1903058-41999,Standard Class,Pauline Webber,Corporate,Shimoga,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-5118,Technology,Accessories,"Logitech Keyboard, USB",145,2,0.0,45,11.00,Medium,2014-12-26,2014-12-30
21675,IN-2014-LC1688558-41940,Second Class,Lena Creighton,Consumer,Bangalore,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-3397,Technology,Accessories,"Belkin Numeric Keypad, Erganomic",177,3,0.0,30,10.84,Medium,2014-10-28,2014-10-30
35956,IN-2013-AT1043558-41607,Standard Class,Alyssa Tate,Home Office,Bellary,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-5101,Technology,Accessories,"Logitech Flash Drive, Programmable",32,1,0.0,10,3.30,High,2013-11-29,2013-12-03

In [113]:
len(data_state['State'])

21

**Getting list of countries where profit and shipping cost are greater than or equal to 2000 and 300 respectively**

In [114]:
data.describe()

              Sales      Quantity      Discount        Profit  Shipping Cost
count  51290.000000  51290.000000  51290.000000  51290.000000   51290.000000
mean     245.977500      3.476545      0.142908     64.023260      26.478567
std      487.562658      2.278766      0.212280    164.466431      57.251373
min        0.000000      1.000000      0.000000      0.000000       1.002000
25%       30.000000      2.000000      0.000000      6.000000       2.610000
50%       85.000000      3.000000      0.000000     18.000000       7.790000
75%      251.000000      5.000000      0.200000     57.000000      24.450000
max    22638.000000     14.000000      0.850000   8399.000000     933.570000

In [120]:
cond4 = (data['Profit']>=2000) & (data['Shipping Cost']>=300)
country_data = data[cond4]
country_list = country_data['Country'].drop_duplicates().tolist()
country_list

['Italy',
 'India',
 'Morocco',
 'Netherlands',
 'United Kingdom',
 'Japan',
 'Lithuania',
 'Australia',
 'Pakistan',
 'United States']

**Finding list of Indian states where people have purchased things under the category 'Technology'**

In [124]:
cond5 = (data['Category']=='Technology') & (data['Country']=='India')
india_technology = data[cond5]
state_technology = india_technology['State'].drop_duplicates().tolist()
state_technology

['Haryana',
 'Jharkhand',
 'Madhya Pradesh',
 'Delhi',
 'Gujarat',
 'Bihar',
 'Kerala',
 'Chhattisgarh',
 'Tamil Nadu',
 'West Bengal',
 'Maharashtra',
 'Karnataka',
 'Rajasthan',
 'Uttar Pradesh',
 'Andhra Pradesh',
 'Telangana',
 'Odisha',
 'Punjab',
 'Assam',
 'Uttarakhand',
 'Puducherry',
 'Jammu and Kashmir']

In [125]:
len(state_technology)

22

**Overall rank of India where the profit is maximum under the category 'Technology'**

In [126]:
print("Max profit:", max(data['Profit']))

Max profit: 8399

In [131]:
cond6 = (data['Profit']>0) & (data['Category']=='Technology')
top_countries = data[cond6]
top_countries.shape

(9915, 21)

In [137]:
sorted_top_countries = top_countries.sort_values(by=['Profit'], ascending=False)
list_sorted_top_countries = sorted_top_countries['Country'].drop_duplicates().tolist()

In [143]:
ranked_data = sorted_top_countries['Country'].drop_duplicates().rank(ascending=False, method='average')
ranked_data

49003      8.0
6591      14.0
362       49.0
215       79.0
313       87.0
81        60.0
39592      9.0
641       54.0
643      129.0
111       99.0
1402      55.0
461      121.0
291       36.0
426      114.0
105      102.0
1256      85.0
1115      81.0
1410      28.0
3675     118.0
1226      95.0
727       70.0
48570    124.0
12        37.0
13013    136.0
87       140.0
3678      30.0
795       23.0
432       63.0
3447      51.0
3640      53.0
         ...
18714     12.0
6871      58.0
15348      7.0
4064     117.0
20755     29.0
6817     119.0
9130      89.0
27486     10.0
10818     61.0
13185     80.0
1072      74.0
4453      15.0
6635      62.0
8633      71.0
797       46.0
20099    112.0
21018     96.0
26410    106.0
13936     78.0
12416     21.0
10918     34.0
15685     65.0
16849     94.0
10671    104.0
26568    107.0
19592     17.0
29037     25.0
29689     69.0
33381     27.0
5060     137.0
Name: Country, Length: 145, dtype: float64

In [144]:
ranked_countries =  sorted_top_countries['Country'].drop_duplicates()
ranked_series = pd.concat([ranked_countries, ranked_data], axis=1)
ranked_series

                                Country  Country
49003                     United States      8.0
6591                             Turkey     14.0
362                            Pakistan     49.0
215                               Japan     79.0
313                               India     87.0
81                              Morocco     60.0
39592                    United Kingdom      9.0
641                         New Zealand     54.0
643                              Brazil    129.0
111                             Germany     99.0
1402                        Netherlands     55.0
461                               China    121.0
291                             Senegal     36.0
426    Democratic Republic of the Congo    114.0
105                              France    102.0
1256                               Iran     85.0
1115                              Italy     81.0
1410                              Spain     28.0
3675                      Cote d'Ivoire    118.0
1226                          Guatemala     95.0
727                           Lithuania     70.0
48570                            Canada    124.0
12                         Saudi Arabia     37.0
13013                        Bangladesh    136.0
87                            Australia    140.0
3678                        South Korea     30.0
795                         Switzerland     23.0
432                              Mexico     63.0
3447                            Nigeria     51.0
3640                          Nicaragua     53.0
...                                 ...      ...
18714                            Uganda     12.0
6871                    Myanmar (Burma)     58.0
15348                           Uruguay      7.0
4064                            Croatia    117.0
20755                       South Sudan     29.0
6817                         Costa Rica    119.0
9130                          Hong Kong     89.0
27486              United Arab Emirates     10.0
10818                          Mongolia     61.0
13185                           Jamaica     80.0
1072                            Lebanon     74.0
4453                            Tunisia     15.0
6635                            Moldova     62.0
8633                              Libya     71.0
797                            Paraguay     46.0
20099                          Djibouti    112.0
21018                        Guadeloupe     96.0
26410                           Eritrea    106.0
13936                            Jordan     78.0
12416                            Taiwan     21.0
10918                      Sierra Leone     34.0
15685                        Martinique     65.0
16849                            Guinea     94.0
10671                          Ethiopia    104.0
26568                 Equatorial Guinea    107.0
19592                              Togo     17.0
29037                         Swaziland     25.0
29689                        Luxembourg     69.0
33381                         Sri Lanka     27.0
5060                            Bahrain    137.0

[145 rows x 2 columns]

**Display the data with min, max, avg and std of 'Profit' and 'Sales' for each sub-category under each category**

In [147]:
grouped_data = data.groupby(by=['Country','Category','Sub-Category'], as_index=True)
grouped_data

In [148]:
functions = [('min_value','min'),('max_value','max'),('mean_value','mean'),('std_value','std')]
grouped_data['Sales','Profit'].agg(functions)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

                                             Sales                         \
                                         min_value max_value   mean_value
Country     Category        Sub-Category
Afghanistan Furniture       Bookcases          731      2070  1400.500000
                            Chairs             417       914   665.500000
                            Furnishings         84       219   134.500000
                            Tables             267      4626  2113.333333
            Office Supplies Appliances         669       669   669.000000
                            Art                 29       177   110.500000
                            Binders             33       251    96.833333
                            Envelopes           79       231   171.000000
                            Fasteners           13        45    29.000000
                            Labels              13        64    39.333333
                            Paper               15       122    77.000000
                            Storage             61       332   189.750000
                            Supplies            69       243   154.333333
            Technology      Accessories        114      1470   408.400000
                            Copiers            427       712   569.500000
                            Machines           346       346   346.000000
                            Phones             412      1168   732.000000
Albania     Furniture       Bookcases          363       414   388.500000
                            Furnishings         58        58    58.000000
            Office Supplies Art                 15       173    73.666667
                            Binders              6        28    17.000000
                            Labels              11        11    11.000000
                            Storage             18       218   113.666667
            Technology      Machines            85      1619   852.000000
                            Phones             182       553   367.500000
Algeria     Furniture       Bookcases          146      1447   556.727273
                            Chairs              63       516   224.500000
                            Furnishings         17       116    77.750000
                            Tables             319       319   319.000000
            Office Supplies Appliances          38      1111   472.625000
...                                            ...       ...          ...
Zambia      Office Supplies Appliances          38       526   218.333333
                            Art                 15       417   148.000000
                            Binders              5       207    51.888889
                            Envelopes            6       244    92.666667
                            Fasteners            7        82    36.250000
                            Labels               9        55    24.500000
                            Paper               17       110    57.200000
                            Storage              9      1023   216.625000
                            Supplies            18        84    57.500000
            Technology      Accessories         40       246   110.000000
                            Copiers            122      1181   415.285714
                            Machines           597      1247   937.000000
                            Phones              88      1272   426.200000
Zimbabwe    Furniture       Bookcases           51        86    68.500000
                            Chairs              49       627   338.000000
                            Furnishings         12        12    12.000000
                            Tables             142       142   142.000000
            Office Supplies Appliances          28       160   114.333333
                            Art                  3       112    26.666667
                            Binders              1        39     6.916667
                            Envelopes            5        42    20.600000
                            Fasteners            4         7     5.000000
                            Labels               2        14     5.750000
                            Paper                7        31    20.500000
                            Storage              3       161    42.666667
                            Supplies            10        66    37.833333
            Technology      Accessories         77        77    77.000000
                            Copiers            154       444   299.000000
                            Machines            14       104    52.500000
                            Phones              21       101    61.000000

                                                         Profit            \
                                            std_value min_value max_value
Country     Category        Sub-Category
Afghanistan Furniture       Bookcases      946.815980       102       848
                            Chairs         351.432070        45       356
                            Furnishings     51.251341         1        79
                            Tables        2254.599817        34       647
            Office Supplies Appliances            NaN       280       280
                            Art             70.011904         8        76
                            Binders         82.990160         0        52
                            Envelopes       80.894994         9        85
                            Fasteners       22.627417         2         2
                            Labels          25.540817         1        22
                            Paper           44.818151         2        42
                            Storage        121.579535        20        70
                            Supplies        87.047880        19       104
            Technology      Accessories    593.736726         4       514
                            Copiers        201.525433         4         7
                            Machines              NaN        13        13
                            Phones         346.302373        24       443
Albania     Furniture       Bookcases       36.062446        39       202
                            Furnishings           NaN         3         3
            Office Supplies Art             86.494701         1        24
                            Binders         15.556349         0         1
                            Labels                NaN         2         2
                            Storage        100.281271         8        54
            Technology      Machines      1084.701802         0       258
                            Phones         262.336616        22        40
Algeria     Furniture       Bookcases      411.036760         8       506
                            Chairs         171.976452        20        61
                            Furnishings     44.701390         0        52
                            Tables                NaN       121       121
            Office Supplies Appliances     403.334295         3       526
...                                               ...       ...       ...
Zambia      Office Supplies Appliances     178.032207         1       131
                            Art            169.925866         4        95
                            Binders         60.727762         0        37
                            Envelopes       99.803140         0       122
                            Fasteners       34.325646         2        18
                            Labels          21.191980         3        19
                            Paper           41.625713         1        39
                            Storage        242.032470         2       184
                            Supplies        31.596413         3        40
            Technology      Accessories     92.419334         6        30
                            Copiers        379.827906         0       261
                            Machines       326.036808        74       263
                            Phones         501.795974         3       407
Zimbabwe    Furniture       Bookcases       24.748737       109       181
                            Chairs         408.707720        56      1087
                            Furnishings      0.000000        20        22
                            Tables                NaN       275       275
            Office Supplies Appliances      74.808645        50       284
                            Art             28.982753         5       133
                            Binders         10.791060         0        89
                            Envelopes       14.536162         9        82
                            Fasteners        1.732051         5         9
                            Labels           5.560276         2        18
                            Paper           11.474610        15        74
                            Storage         51.879668         6       124
                            Supplies        25.031314        12        55
            Technology      Accessories           NaN        59        59
                            Copiers        205.060967       257       371
                            Machines        42.696604        20       173
                            Phones          56.568542        47       169


                                          mean_value   std_value
Country     Category        Sub-Category
Afghanistan Furniture       Bookcases     475.000000  527.501659
                            Chairs        200.500000  219.910209
                            Furnishings    32.333333   32.240761
                            Tables        415.000000  332.555259
            Office Supplies Appliances    280.000000         NaN
                            Art            33.250000   30.761177
                            Binders        21.000000   20.109699
                            Envelopes      39.333333   40.253364
                            Fasteners       2.000000    0.000000
                            Labels         13.333333   10.969655
                            Paper          14.000000   18.832596
                            Storage        46.000000   22.671568
                            Supplies       56.333333   43.431939
            Technology      Accessories   112.000000  224.854397
                            Copiers         5.500000    2.121320
                            Machines       13.000000         NaN
                            Phones        236.500000  199.011725
Albania     Furniture       Bookcases     120.500000  115.258405
                            Furnishings     3.000000         NaN
            Office Supplies Art             9.666667   12.503333
                            Binders         0.500000    0.707107
                            Labels          2.000000         NaN
                            Storage        35.000000   24.020824
            Technology      Machines      129.000000  182.433550
                            Phones         31.000000   12.727922
Algeria     Furniture       Bookcases     146.636364  146.778250
                            Chairs         36.500000   16.416455
                            Furnishings    16.000000   18.228706
                            Tables        121.000000         NaN
            Office Supplies Appliances    113.750000  169.751709
...                                              ...         ...
Zambia      Office Supplies Appliances     46.333333   50.246061
                            Art            36.500000   45.399339
                            Binders        11.444444   13.473224
                            Envelopes      33.500000   47.035093
                            Fasteners       7.250000    7.274384
                            Labels          6.500000    6.220932
                            Paper          16.000000   16.552945
                            Storage        52.500000   52.850733
                            Supplies       21.500000   16.010413
            Technology      Accessories    17.000000   10.165300
                            Copiers        67.571429   87.699976
                            Machines      196.000000  105.825328
                            Phones        135.200000  175.334537
Zimbabwe    Furniture       Bookcases     145.000000   50.911688
                            Chairs        571.500000  729.027091
                            Furnishings    21.000000    1.414214
                            Tables        275.000000         NaN
            Office Supplies Appliances    156.000000  118.541132
                            Art            41.833333   43.348451
                            Binders        13.083333   25.328598
                            Envelopes      34.600000   30.451601
                            Fasteners       7.666667    2.309401
                            Labels          6.750000    7.544314
                            Paper          36.750000   25.747168
                            Storage        51.111111   43.149289
                            Supplies       37.166667   15.917496
            Technology      Accessories    59.000000         NaN
                            Copiers       314.000000   80.610173
                            Machines       76.500000   72.958893
                            Phones        108.000000   86.267027

[2009 rows x 8 columns]